.TH "pid.c" 3 "Version 1.0.1" "PID for Arduino-based Car" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pid.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <Controller\&.c>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPIDController\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPID_Init\fP (\fBPIDController\fP *pid, double Kp, double Ki, double Kd, double setpoint)"
.br
.ti -1c
.RI "double \fBPID_Update\fP (\fBPIDController\fP *pid, double measured_value)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PID for Arduino-based Car from the source code\&.
