.TH "PIDController" 3 "Version 1.0.1" "PID for Arduino-based Car" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PIDController
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBKp\fP"
.br
.ti -1c
.RI "double \fBKi\fP"
.br
.ti -1c
.RI "double \fBKd\fP"
.br
.ti -1c
.RI "double \fBsetpoint\fP"
.br
.ti -1c
.RI "double \fBerror\fP"
.br
.ti -1c
.RI "double \fBlast_error\fP"
.br
.ti -1c
.RI "double \fBintegral\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PID for Arduino-based Car from the source code\&.
